### PR TITLE
StorageClasses now allow volume expansion

### PR DESCRIPTION
**Pull request by mvladev**
**How to categorize this PR?**

/area storage
/kind enhancement
/priority normal
/platform aws

**What this PR does / why we need it**:

Allows claims for EBS volumes to be resized.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

`AllowVolumeExpansion` is [not immutable](https://github.com/kubernetes/kubernetes/blob/6c6fd9c575457885dfbd07fe5df43df9a4e08a22/pkg/apis/storage/validation/validation.go#L59-L76).

**Release note**:

```improvement user
`StorageClasses` now allow for expansion of PVCs.
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Volume resizing is still alpha for the aws-ebs-csi-driver which we use starting from v1.18. I am not sure that we want to enable by default this for the csi storageclasses. Ref https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/README.md#features-1

**Comment by ialidzhikov** [comment]
> Volume resizing is still alpha for the aws-ebs-csi-driver which we use starting from v1.18. I am not sure that we want to enable by default this for the csi storageclasses. Ref https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/README.md#features-1

Or the docs of the aws-ebs-csi-driver are outdated?

**Comment by ialidzhikov** [comment]
> Or the docs of the aws-ebs-csi-driver are outdated?

Ref https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/531

**Comment by mvladev** [comment]
Rebased and fixed conflict.

**Pull request merged**
