### PR TITLE
Updated cluster creation tutorial - AWS

### PR DESCRIPTION
**Pull request by n-boshnakov**
**How to categorize this PR?**

/area documentation
/kind enhancement
/platform aws

**What this PR does / why we need it**:
This PR updates the content and screenshots of the Kubernetes cluster creation tutorial with AWS in order to unify it with other similar tutorials.
**Which issue(s) this PR fixes**:
Part of [gardener/documentation#287](https://github.com/gardener/documentation/issues/287).

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Comment by n-boshnakov** [comment]
PR will be fixed and reuploaded

**Review by ialidzhikov — CHANGES_REQUESTED** [review]
Thanks for the PR. Can you squash to single commit as there is a merge commit and a lot of unrelated commits part of this PR?

**Review by ialidzhikov — COMMENTED** [review]
You still have a merge conflict. Can you please resolve it?

**Review by n-boshnakov — COMMENTED** [review]
/lgtm

**Comment by n-boshnakov** [comment]
> /lgtm

This comment is due to an internal agreement between @ialidzhikov and myself. After reviewing and approving the content of my commits, he helped with squashing them and wanted me to go over the changes to make sure everything was correct. I notified him via the lgtm command.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
