### PR TITLE
fix issue with dup zone validation

### PR DESCRIPTION
**Pull request by kon-angelo**
**How to categorize this PR?**

/area control-plane
/kind bug
/platform aws

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Fix an issue that allows duplicate zones in the infrastructure.
```

### CODE REVIEW

**Review by MartinWeindel — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
Isn't this a breaking change? What happens to Shoots that already have duplicate zones in their infrastructureConfig? Do we have such Shoots on our landscapes?

**Comment by kon-angelo** [comment]
@ialidzhikov  It shouldn't be a breaking change. For existing zones (pre-update), it just adds them to the set, but it should disallow you from adding even more duplicate zones. Before this change you could theoretically add already duplicated zones ad-infinitum.

**Comment by ialidzhikov** [comment]
Ah, I see. It is only for new zones that are being added. You are right. Thanks for explaining!

**Pull request merged**
