### PR TITLE
Vendor `gardener@v1.83.2`

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area open-source
/kind enhancement
/platform aws

**What this PR does / why we need it**:
Vendor `gardener@v1.83.2` and adapt breaking changes.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
~Need to vendor a gardener version containing https://github.com/gardener/gardener/pull/8789, Hence in draft.~

**Release note**:

```other operator
The following golang dependencies have been upgraded :
- `gardener/gardener`: `v1.81.6`->`v1.83.2`
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
It will not work without https://github.com/gardener/gardener/pull/8855, will update to `v1.84.1` which has this fix.

**Comment by shafeeqes** [comment]
> It will not work without [gardener/gardener#8855](https://github.com/gardener/gardener/pull/8855), will update to `v1.84.1` which has this fix.

Hmm, this is not related to the above PR. Will check.

**Comment by shafeeqes** [comment]
The `make verify` passes for me locally without issues.

**Comment by shafeeqes** [comment]
@kon-angelo PTAL!

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
