### PR TITLE
Remove AWS gp2 StorageClass

### PR DESCRIPTION
**Pull request by StenlyTU**
**How to categorize this PR?**

/area storage
/kind enhancement
/platform aws

**What this PR does / why we need it**:
Removing the gp2 StorageClass for AWS

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
@dguendisch @hendrikKahl @BeckerMax 

**Release note**:

```other user
Removing the gp2 StorageClass for AWS
```

### CODE REVIEW

**Review by dkistner — APPROVED** [review]

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Comment by dguendisch** [comment]
This is probably legacy/not-in-use, but does this need adaptation as well?
https://github.com/gardener/gardener-extension-provider-aws/blob/master/.landscaper/blueprint/deploy-execution-manifests.yaml#L762

**Comment by kon-angelo** [comment]
@dguendisch thank you for pointing that out. This is for the VMs and we can do it in a separate PR

**Comment by ialidzhikov** [comment]
Isn't there any logic relying the StorageClass of existing PVC to be present?

**Comment by StenlyTU** [comment]
Didn't manage to find anything into KCM & CSI-driver((all 6 containers)) pods related to the missing storageclass even after pod's recreation.

**Comment by StenlyTU** [comment]
As @ialidzhikov suggested couldn't find anything in the logs of kube-scheduler related to the deleted StorageClass: gp2.

**Comment by kon-angelo** [comment]
@ialidzhikov if the volume is already provisioned then nothing breaks AFAIK. It only matters during provisioning.

**Pull request merged**
