### PR TITLE
Expose logs from user exposed components in the new way

### PR DESCRIPTION
**Pull request by Kristian-ZH**
**How to categorize this PR?**

/area logging
/kind enhancement
/platform aws

**What this PR does / why we need it**:
Adapt the extension to https://github.com/gardener/gardener/pull/4060

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
This seems to not be backwards compatible with older Gardener versions, correct?

**Comment by Kristian-ZH** [comment]
Yes, it will completely replace the older version

**Comment by rfranzke** [comment]
I think @ialidzhikov asked this already as well. Generally, we try to be backwards-compatible for at least a couple of releases, so what's the proposed way forward with these PRs?

**Comment by Kristian-ZH** [comment]
My idea to not make it backwards-compatible was that the users users/operators will have two different dashboards which will look in the same way and will contain the same information. Also currently we are making one dashboard for each exposed component, which makes the navigation between them a way harder. 

But if you see any value in keeping both approaches alive for some time then I will do it.

**Comment by rfranzke** [comment]
My concern is rather: When somebody deploys an AWS extension version with this PR and a Gardener version without https://github.com/gardener/gardener/pull/4060 - what will happen? My understanding is that there won't be any dashboard at all, right?

**Comment by Kristian-ZH** [comment]
Yes, if that happens there won't be any dashboards for ccm and csi-driver

**Review by rfranzke — APPROVED** [review]
/lgtm
/cc @ialidzhikov as he's currently a new release

**Comment by ialidzhikov** [comment]
> Yes, if that happens there won't be any dashboards for ccm and csi-driver

Is this PR still a breaking change against a Gardener version without gardener/gardener#4060?

**Comment by Kristian-ZH** [comment]
No, it is backwards compatible now.

**Pull request merged**
