### PR TITLE
:sparkle: Enable default SSE for s3 bucket

### PR DESCRIPTION
**Pull request by swapnilgm**
Signed-off-by: Swapnil Mhamane <swapnil.mhamane@sap.com>

**How to categorize this PR?**

/area security
/kind enhancement
/priority critical
/platform aws

**What this PR does / why we need it**:
This PR configures the bucket with SSE encryption
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Server side encryption will be enabled for provisioned s3 buckets.
```

### CODE REVIEW

**Comment by vlerenc** [comment]
Thank you for taking this up. Please consider that we have to support encryption for all infrastructures, not only AWS.

**Comment by swapnilgm** [comment]
Yes, I checked with all cloud providers. GCS, Openstack, Azure enables the encryption by default. No need for additional configuration. For alicloud OSS, its similar to AWS. But i have issue with my credentials there (expire, need to reset by admin). Will check and confirm the changes there as well.

**Comment by rfranzke** [comment]
@swapnilgm this will enable this encryption only for new buckets, right?

**Comment by swapnilgm** [comment]
No. On reconcilation, it will enable encryption for old buckets as well. Post enabling bucket encryption, only new objects in buckets will be encrypted at rest. Old object will still be unencrypted at rest.  Considering we garbage collect old backups/objects over the period all unencrypted objects will be removed.

**Comment by rfranzke** [comment]
Great, thanks @swapnilgm

**Pull request merged**
