### PR TITLE
bump prometheus/client_golang

### PR DESCRIPTION
**Pull request by FriedrichWilken**
this PR bumps `github.com/prometheus/client_golang` and `sigs.k8s.io/controller-runtime` to `v0.11.1`.

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @FriedrichWilken for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by rfranzke** [comment]
@FriedrichWilken Why there are these changes for the `vendor/github.com/gardener/gardener` folder?

**Comment by FriedrichWilken** [comment]
@rfranzke I did the rebase, added my changes on top. Since these where changes to the `go.mod` file I ran `go mod tidy` and `go mod vendor` again. The changes to `vendor/github.com/gardener/gardener` must have happened because a past PR did changes to `gardener` in the mod file without vendoring them. In fact, if you take the latest `master` and run `go mod vendor`, it will result into the same changes.

Maybe I misunderstand the way you handle `go.mod` and your `vendor/` dir.

**Comment by rfranzke** [comment]
Can you run `make revendor` instead?

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
