### PR TITLE
Improve logging for csi-driver-node

### LINKED ISSUE #418: Increase log verbosity of csi-driver-node
**How to categorize this issue?**

/area storage logging
/kind enhancement

**What would you like to be added**:

Let's increase the log verbosity of the `csi-driver` container in `csi-driver-node` (at least to 4).

However, on log level 4 and above, csi-driver logs the frequent `NodeGetCapabilities` and `NodeGetVolumeStats` calls (roughly once per 2 minutes for each PV), which are not really that interesting:
```
I0930 13:19:44.947404       1 node.go:498] NodeGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0930 13:19:44.949556       1 node.go:435] NodeGetVolumeStats: called with args {VolumeId:vol-abcdef VolumePath:/var/lib/kubelet/pods/some-pod-uid/volumes/kubernetes.io~csi/pv-shoot--timebertt--test-some-uid/mount StagingTargetPath: XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0930 13:21:09.072947       1 node.go:498] NodeGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0930 13:21:09.074569       1 node.go:435] NodeGetVolumeStats: called with args {VolumeId:vol-abcdef VolumePath:/var/lib/kubelet/pods/some-pod-uid/volumes/kubernetes.io~csi/pv-shoot--timebertt--test-some-uid/mount StagingTargetPath: XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
```

Right now, we don't keep the system-component logs in the logging stack. But once we do, we probably want to filter out these logs.

**Why is this needed**:

We need more logs regarding critical volume operations that operators want to analyze.
Currently `csi-driver-node` is very quiet on log level 3.

### PR DESCRIPTION
**Pull request by MartinWeindel**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform aws

**What this PR does / why we need it**:
Improve logging for csi-driver-node to log mount operation details.

**Which issue(s) this PR fixes**:
Fixes #418

**Special notes for your reviewer**:

**Release note**:

```other operator
Improve logging for csi-driver-node to provide mount operation details.
```

### CODE REVIEW

**Comment by MartinWeindel** [comment]
As discussed in the issue #418, the `vmodule` option can be used to set the verbose level per file pattern.
The chosen pattern avoids the periodic logging of "NodeGetCapabilities" and "NodeGetVolumeStats" and provides details about the mount operations.

Compare these two logs on creating and deleting a PVC. The first with the current logging settings, the second with the new settings.

1. Old
```txt
I1212 15:22:11.593976       1 node.go:91] regionFromSession Node service
I1212 15:22:11.594025       1 metadata.go:85] retrieving instance data from ec2 metadata
I1212 15:22:11.595711       1 metadata.go:92] ec2 metadata is available
I1212 15:22:11.596321       1 metadata_ec2.go:25] regionFromSession
I1212 15:23:34.762866       1 mount_linux.go:525] Disk "/dev/nvme1n1" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/nvme1n1]
I1212 15:23:35.096840       1 mount_linux.go:535] Disk successfully formatted (mkfs): ext4 - /dev/nvme1n1 /var/lib/kubelet/plugins/kubernetes.io/csi/ebs.csi.aws.com/80706f693d9c81a55aea3fe36a6e60d223cca8586d8dddacc583d6a7bddc6303/globalmount
I1212 15:23:35.096966       1 mount_linux.go:244] Detected OS without systemd
I1212 15:23:35.120519       1 resizefs_linux.go:124] ResizeFs.needResize - checking mounted volume /dev/nvme1n1
``` 

2. New
```txt
I1212 15:26:02.759387       1 driver.go:73] Driver: ebs.csi.aws.com Version: v1.13.0
I1212 15:26:02.759431       1 node.go:91] regionFromSession Node service
I1212 15:26:02.759445       1 metadata.go:85] retrieving instance data from ec2 metadata
I1212 15:26:02.761013       1 metadata.go:92] ec2 metadata is available
I1212 15:26:02.761595       1 metadata_ec2.go:25] regionFromSession
I1212 15:26:02.763081       1 mount_linux.go:275] Cannot create temp dir to detect safe 'not mounted' behavior: mkdir /tmp/kubelet-detect-safe-umount1239896977: read-only file system
I1212 15:26:02.764385       1 driver.go:143] Listening for connections on address: &net.UnixAddr{Name:"/csi/csi.sock", Net:"unix"}
I1212 15:26:29.443253       1 mount_linux.go:563] Attempting to determine if disk "/dev/nvme1n1" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/nvme1n1])
I1212 15:26:29.455511       1 mount_linux.go:566] Output: ""
I1212 15:26:29.455532       1 mount_linux.go:525] Disk "/dev/nvme1n1" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/nvme1n1]
I1212 15:26:29.787972       1 mount_linux.go:535] Disk successfully formatted (mkfs): ext4 - /dev/nvme1n1 /var/lib/kubelet/plugins/kubernetes.io/csi/ebs.csi.aws.com/db48b98bca95fbeff421efa36e8536ac9547e9e0764dec01cb2622e4a97bc3a7/globalmount
I1212 15:26:29.787999       1 mount_linux.go:553] Attempting to mount disk /dev/nvme1n1 in ext4 format at /var/lib/kubelet/plugins/kubernetes.io/csi/ebs.csi.aws.com/db48b98bca95fbeff421efa36e8536ac9547e9e0764dec01cb2622e4a97bc3a7/globalmount
I1212 15:26:29.788083       1 mount_linux.go:244] Detected OS without systemd
I1212 15:26:29.788095       1 mount_linux.go:219] Mounting cmd (mount) with arguments (-t ext4 -o defaults /dev/nvme1n1 /var/lib/kubelet/plugins/kubernetes.io/csi/ebs.csi.aws.com/db48b98bca95fbeff421efa36e8536ac9547e9e0764dec01cb2622e4a97bc3a7/globalmount)
I1212 15:26:29.802429       1 mount_linux.go:563] Attempting to determine if disk "/dev/nvme1n1" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/nvme1n1])
I1212 15:26:29.809796       1 mount_linux.go:566] Output: "DEVNAME=/dev/nvme1n1\nTYPE=ext4\n"
I1212 15:26:29.809816       1 resizefs_linux.go:124] ResizeFs.needResize - checking mounted volume /dev/nvme1n1
I1212 15:26:29.860423       1 node_linux.go:151] NodePublishVolume: creating dir /var/lib/kubelet/pods/89f489f3-0c06-49fc-b5fe-63f69609511b/volumes/kubernetes.io~csi/pv-shoot--dev--tstaws24-491300a3-ec54-47f7-96a3-544a047f4a21/mount
I1212 15:26:29.860558       1 mount_linux.go:219] Mounting cmd (mount) with arguments (-t ext4 -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/ebs.csi.aws.com/db48b98bca95fbeff421efa36e8536ac9547e9e0764dec01cb2622e4a97bc3a7/globalmount /var/lib/kubelet/pods/89f489f3-0c06-49fc-b5fe-63f69609511b/volumes/kubernetes.io~csi/pv-shoot--dev--tstaws24-491300a3-ec54-47f7-96a3-544a047f4a21/mount)
I1212 15:26:29.862137       1 mount_linux.go:219] Mounting cmd (mount) with arguments (-t ext4 -o bind,remount /var/lib/kubelet/plugins/kubernetes.io/csi/ebs.csi.aws.com/db48b98bca95fbeff421efa36e8536ac9547e9e0764dec01cb2622e4a97bc3a7/globalmount /var/lib/kubelet/pods/89f489f3-0c06-49fc-b5fe-63f69609511b/volumes/kubernetes.io~csi/pv-shoot--dev--tstaws24-491300a3-ec54-47f7-96a3-544a047f4a21/mount)
I1212 15:26:42.429951       1 mount_linux.go:361] Unmounting /var/lib/kubelet/pods/89f489f3-0c06-49fc-b5fe-63f69609511b/volumes/kubernetes.io~csi/pv-shoot--dev--tstaws24-491300a3-ec54-47f7-96a3-544a047f4a21/mount
I1212 15:26:42.532084       1 mount_linux.go:361] Unmounting /var/lib/kubelet/plugins/kubernetes.io/csi/ebs.csi.aws.com/db48b98bca95fbeff421efa36e8536ac9547e9e0764dec01cb2622e4a97bc3a7/globalmount
```

**Comment by MartinWeindel** [comment]
Thanks to @istvanballok for the hint of the `vmodule` option of `klog`.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Comment by kon-angelo** [comment]
@MartinWeindel do you plan on replicating this PR for the other providers ?

**Pull request merged**
