### PR TITLE
update mcm to use worker secret ref. for the machine class credentialsSecretRef

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**How to categorize this PR?**

/area quality
/kind enhancement
/priority normal
/platform aws

**What this PR does / why we need it**:

Uses the machine classes  .{spec.}credentialsSecretRef field. It is a reference to a secret containing only the credentials, while today's .{spec.}secretRef still contains the user-data. See [here for more details](https://github.com/gardener/machine-controller-manager/pull/578).

Uses the worker's secret reference as the credentialsSecretRef.
This means all worker pools use the same "cloudprovider" secret containing only the cloud provider credentials.
The existing MachineClass SecretReference then only contains the user data that is different for each pool. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Reducing credential update complexity by all the machine classes using the new .{spec.}credentialsSecretRef field.
This means all worker pools use the same "cloudprovider" secret containing only the cloud provider credentials.
The existing MachineClass SecretReference only contains the user data that is different for each pool.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Changes look great, will test it and come back

**Comment by prashanth26** [comment]
We can go ahead with merging this PR first. I will rebase these changes on https://github.com/gardener/gardener-extension-provider-aws/pull/212 on this is merged.

**Comment by rfranzke** [comment]
@danielfoehrKn can you rebase now? I guess no more revendoring is necessary because it's already done on `master` (#237)

**Review by prashanth26 — APPROVED** [review]
/lgtm

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/squash

**Review by rfranzke — APPROVED** [review]
/lgtm
/hold until v1.19 got released

**Comment by prashanth26** [comment]
Hi @danielfoehrKn , Hi Colleagues,

I was going through all the changes for `provider-aws` release over the weekend. And I realized that there is a corner case that we might have missed that could potentially cause clusters hanging during deletion. 

We have [this method](https://github.com/gardener/gardener/blob/master/extensions/pkg/controller/worker/genericactuator/actuator_delete.go#L160) that waits until all machine objects are cleaned up by MCM before deleting it. However, this does not check for the MCM finalizers on `cloudprovider` which will exist with this change as MCM uses `cloudprovider` secret now. 

I tried to reproduce this scenario with several shoot deletions however was unsuccessful has I think this case can be hit only when `cloudprovider` finalizer update fails (as currently finalizer removal is too fast and the race condition isn't hit). However, I am pretty confident that we need this check to avoid such cases, and we could verify this with unit tests to reproduce this case. 

The check would be to wait until the finalizer is removed for `cloudprovider` secret similar to this - https://github.com/gardener/gardener/blob/master/extensions/pkg/controller/worker/genericactuator/actuator_delete.go#L224. I think we need this change in g/g and revendor it to all providers before releasing any of the extension providers. WDYT?

**Comment by ialidzhikov** [comment]
In our sync about this we agreed to add the `gardener.cloud/purpose=machineclass` label to the worker `.spec.secretRef` (aka cloudprovider Secret) and adapt the check in https://github.com/gardener/gardener/blob/ee91337bdf786a45a9b025cfc5ca883936240475/extensions/pkg/controller/worker/genericactuator/actuator_delete.go#L231-L235 to check only for the removal of the mcm finalizer.

But checking the code now again, I guess this won't work as we have a `cleanupMachineClassSecrets` func (ref https://github.com/gardener/gardener/blob/v1.15.3/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go#L181-L184) that will the delete the cloudprovider secret assuming that it is a machine class secret that is stale.

**Comment by prashanth26** [comment]
> https://github.com/gardener/gardener/blob/ee91337bdf786a45a9b025cfc5ca883936240475/extensions/pkg/controller/worker/genericactuator/actuator_delete.go#L231-L235

Yes, Ismail, this wouldn't work. 

The check would be to wait until the finalizer is removed for `cloudprovider` secret similar to this here. However instead of waiting for the secret deletion, we would have to wait only until finalizer is removed.

**Pull request merged**
