### PR TITLE
Vendor gardener/gardener@v1.32.0

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**
/area open-source
/kind enhancement

**What this PR does / why we need it**:
Revendor `gardener/gardener@v1.32.0`.

**Release note**:
```other operator
NONE
```

### CODE REVIEW

**Comment by vpnachev** [comment]
You can remove the `./test/...` in the generate step in Makefile as it is no longer needed
https://github.com/gardener/gardener-extension-provider-aws/blob/d610dabb06a519bb05a656b1e4eeb7125fe83a43/Makefile#L124

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
