### PR TITLE
Revendor gardener (`k/*@v0.19`) and controller-runtime `v0.7.1`

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source
/kind enhancement
/priority normal
/platform aws

**What this PR does / why we need it**:
Revendor gardener (`k/*@v0.19`) and controller-runtime `v0.7.1`

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/3109

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by timebertt — APPROVED** [review]

**Pull request merged**
