### PR TITLE
Update bastion image AMI

### PR DESCRIPTION
**Pull request by kon-angelo**
**How to categorize this PR?**

/area control-plane
/kind test
/platform aws

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Update bastion integration test AMI image
```

### CODE REVIEW

**Comment by kon-angelo** [comment]
/invite @tedteng 

@tedteng can we find a more "sustainable" way to get the image AMIs for the test ? The old one is seemingly gone so maybe we need to rethink how we resolve them.

**Review by tedteng — APPROVED** [review]

**Comment by tedteng** [comment]
> can we find a more "sustainable" way to get the image AMIs for the test ? The old one is seemingly gone so maybe we need to rethink how we resolve them.

@kon-angelo I will work on that

**Review by MartinWeindel — APPROVED** [review]
/lgtm

**Pull request merged**
