### PR TITLE
mtu customizer should use default network interface instead of eth0

### LINKED ISSUE #52: MTU customizer unit fails if eth0 not available
**What happened**:

When creating a Shoot with an ubuntu image, the mtu-customizer.service (systemd) fails because it expects the existence of eth0 network interface.
The mtu customizer should the mtu of the primary network interface to a common value 1460. 

Tested on AWS with coreos and ubuntu.

**What you expected to happen**:
mtu-customizer service should have run successfully.
MTU should be 1460.

**How to reproduce it (as minimally and precisely as possible)**:

 - AWS Shoot with a machine type that is capable of [ENA](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html) 
like m5.large 
- Machine image ubuntu (used ubuntu in version 18.4.20190617)

Execute `systemctl status mtu-customizer.service` and observe that it is in failed status.
Execute `ifconfig | grp eth0` and see that eth0 is missing.

**Anything else we need to know?**:

Ubuntu defaults to using the ENA network interface that is not eth0.
**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**What this PR does / why we need it**:

See attached issue.

**Which issue(s) this PR fixes**:
Fixes #52 

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by vpnachev** [comment]
duplicate of #50 :smile:

**Comment by rfranzke** [comment]
Thanks @danielfoehrKn for scouting and pro-actively providing a fix! Though, #50 was opened shortly before... :( Can we close this in favor of #50?

**Comment by zanetworker** [comment]
Nice :) 

I can think of some problems though (which at the moment we don't have).  But imagine that we have VM with more than one network interface, your script fetches only the default and sets the MTU on it, the other one will still be left with the old MTU.

**Comment by danielfoehrKn** [comment]
Sure, closing this.

**Pull request closed without merging**
