### PR TITLE
Vendor gardener/gardener@v1.91.0 and add cluster-autoscaler options to machine deployment

### PR DESCRIPTION
**Pull request by aaronfern**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement
/platform aws

**What this PR does / why we need it**:
This PR does the following
1. Vendor `gardener/gardener:v1.91.0`
2. Adds `cluster-autoscaler` options for worker groups from workers to machine deployments. These options allow users to specify some `cluster-autoscaler` specific for worker groups

**Which issue(s) this PR fixes**:
Fixes partially gardener/autoscaler#240

**Special notes for your reviewer**:
- `Autoscaler` will read these values from annotations in the `machineDeployment` (ref: https://github.com/gardener/autoscaler/pull/257)
- These values are specified in the shoot via `spec.provider.workers.clusterAutoscaler` and are added to the worker (ref: https://github.com/gardener/gardener/pull/9245)

**Release note**:

```other operator
NodeGroupAutoscalingOptions can now be specified per worker group via the worker through the field `worker.spec.pools.clusterAutoscaler`
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
Hi @aaronfern, Would it be enough to have https://github.com/gardener/gardener-extension-provider-aws/pull/901/commits/3315a1a63a5d45aefb1f02e8aefe20b7c9a65f6c in https://github.com/gardener/gardener-extension-provider-aws/pull/901?

**Comment by aaronfern** [comment]
Hey @shafeeqes 
Yes, that should be fine. Thanks!
Can you please update the PR description and release notes of your PR to capture these changes?

**Comment by aaronfern** [comment]
Closing this PR in favour of #901 
/close

**Comment by shafeeqes** [comment]
> Hey @shafeeqes Yes, that should be fine. Thanks! Can you please update the PR description and release notes of your PR to capture these changes?

Done, PTAL!

**Pull request closed without merging**
