### PR TITLE
Expose MCM logs to the end-user

### PR DESCRIPTION
**Pull request by vlvasilev**
**How to categorize this PR?**

/area logging
/kind enhancement
/platform aws

**What this PR does / why we need it**:
With this PR we allow end-users to see the MCM logs.
The logs will be visible after the merge of [g/g#4387](https://github.com/gardener/gardener/pull/4387)

**Which issue(s) this PR fixes**:
Рartially fixes [g/g#4340](https://github.com/gardener/gardener/issues/4340)

**Special notes for your reviewer**:

**Release note**:

```other operator
machine-controller-manager logs are exposed to the end-users
```

### CODE REVIEW

**Comment by dkistner** [comment]
Does this PR depend on https://github.com/gardener/gardener/pull/4387?
Or is it just without this merged and release in g/g the logs from mcm can't be displayed?

So far it looks good to me, but I'm not an expert in this area so would appreciate an opinion from @Kristian-ZH @istvanballok
/invite @Kristian-ZH @istvanballok

**Comment by vlvasilev** [comment]
> Does this PR depend on [gardener/gardener#4387](https://github.com/gardener/gardener/pull/4387)?
> Or is it just without this merged and release in g/g the logs from mcm can't be displayed?

This PR does not depend on  [gardener/gardener#4387](https://github.com/gardener/gardener/pull/4387).
The log will be stored in the Loki under user tenant but will be not visible until the above PR is merged.

**Review by dkistner — DISMISSED** [review]
/lgtm
/hold due to ongoing release validation
cc @ialidzhikov

**Comment by ialidzhikov** [comment]
/invite @Kristian-ZH @istvanballok 
for review

**Comment by Kristian-ZH** [comment]
I see that you have created a dedicated `rewrite_tag` filter for the MCM, which is different approach than the previous (ccm, csi-driver), where all components were in one filter.

If we want to follow the new approach, maybe the CCM and the CSI-driver also should be splitted  in two different filters.

**Comment by Kristian-ZH** [comment]
Also this PR: https://github.com/gardener/gardener/pull/4387 is still not released.
If we want to keep the backwards-compatibility (older version of Gardener combined with newer version of this extension) we can also keep the old logic of exposing components for a few more releases.

**Comment by vlvasilev** [comment]
> Also this PR: [gardener/gardener#4387](https://github.com/gardener/gardener/pull/4387) is still not released.
> If we want to keep the backwards-compatibility (older version of Gardener combined with newer version of this extension) we can also keep the old logic of exposing components for a few more releases.

Who said that I had removed the old logic?

> I see that you have created a dedicated rewrite_tag filter for the MCM, which is different approach than the previous (ccm, csi-driver), where all components were in one filter.

The filter will become a lot of complex and hard to read so I decided to separate it.

**Comment by Kristian-ZH** [comment]
> Who said that I had removed the old logic?

Opps, my bad...

> The filter will become a lot of complex and hard to read so I decided to separate it.

Then what about creating a different filters for CCM and CSI-driver also. E.g. Each component to have its own filter ?

**Comment by vlvasilev** [comment]
> Then what about creating a different filters for CCM and CSI-driver also. E.g. Each component to have its own filter ?

You are welcome to do it if you wish. I have no time for that.

**Review by vpnachev — APPROVED** [review]
/lgtm

**Pull request merged**
