### PR TITLE
Upgrade terraformer to v2.13.0, a version that uses terraform 0.13

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform aws

**What this PR does / why we need it**:
Upgrades `terraformer` image to v2.13.0, a version that uses `terraform` 0.13.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release Notes**:

``` other operator github.com/gardener/terraformer #105 @stoyanr
terraform has been upgraded to 0.13.7
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Does this also work for existing shoots? https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers talks about some state migration and a new `terraform state replace-provider` command that should be called?

**Comment by stoyanr** [comment]
> Does this also work for existing shoots? https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers talks about some state migration and a new terraform state replace-provider command that should be called?

I am currently in the process of testing and fixing this (hence `Draft`). As a matter of fact, it doesn't work even with the non-inhouse providers, the `terraform state replace-provider` command is needed there as well.

**Comment by ialidzhikov** [comment]
/hold
as we want to tackle few existing terraform issue before the update to terraform@0.13

**Comment by stoyanr** [comment]
/invite @ialidzhikov @dkistner 

The new terraform version has already been tested with AWS, see https://github.com/gardener/terraformer/pull/105 for more details.

**Comment by ialidzhikov** [comment]
/unhold

As the issues mentioned in https://github.com/gardener/gardener-extension-provider-aws/pull/439#issuecomment-974007554 are now mitigated/fixed.

**Review by dkistner — APPROVED** [review]
/lgtm

**Pull request merged**
