### PR TITLE
Add priorityClass for mtu-customizer

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area quality robustness
/kind bug
/priority normal
/platform aws

**What this PR does / why we need it**:

Add priorityClass for `mtu-customizer`.
Without raised priority for the `DaemonSet` it might not be scheduled in favor of other workload, e.g. `etcd` pods.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
The Pods of the `mtu-customizer` DaemonSet now use the same `PriorityClass` like `provider-aws` Pods, to ensure the Pods are always scheduled on all Nodes.
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]
/lgtm

Thanks, can you also open a cherry-pick PR for `release-v1.20`?

**Review by prashanth26 — DISMISSED** [review]
/lgtm

**Comment by prashanth26** [comment]
`verify` step seems to be failing. make generate needs to be run again.

**Comment by timebertt** [comment]
> Thanks, can you also open a cherry-pick PR for `release-v1.20`?

Done.

**Comment by timebertt** [comment]
Sorry for the multiple pushes.
Forgot to generate the ctrlreg, then used helm 3 to generate, but now I finally got it :D

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
