### PR TITLE
Vendor gardener/gardener@v1.39.4

### PR DESCRIPTION
**Pull request by ialidzhikov**
/kind bug
/platform aws

Compared to `gardener/gardener@v1.39.0`, `gardener/gardener@v1.39.4` contains the following fixes that are related to the extension library:
- https://github.com/gardener/gardener/pull/5339
- https://github.com/gardener/gardener/pull/5408
- https://github.com/gardener/gardener/pull/5417

Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/482

**Release note**:

```bugfix operator
The following dependency is updated:
- github.com/gardener/gardener: v1.39.0 -> v1.39.4
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
/milestone v1.33
as the broken Worker restore operation would be a regression compared to the `provider-aws@v1.32.0`

**Review by dkistner — DISMISSED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
/hold
as I plan to update this PR with vendoring of v1.39.4

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by dkistner — APPROVED** [review]
/lgtm

**Pull request merged**
