### PR TITLE
Add zone label to machine classes

### LINKED ISSUE #77: Introduce `zone` label on the MachineClass.
**What would you like to be added**:  We recently introduced the scale-to-zero feature for the cluster-autoscaler. This feature requires the autoscaler to know the `zone` for which the MachineClass/MachineDeployment is being created as part of its sub-functionality. Following are the related discussions/issues: 
- https://github.com/gardener/autoscaler/pull/26#discussion_r365868415
- https://github.com/gardener/autoscaler/issues/34

It would mean, autoscaler can't scale-up from zero for statefulset workload. 

Also to note, we plan to re-work on the architecture of the scale-to-zero feature. There we may add `zone` field in the AWSMachineClass's Spec. But the approach there has to be completely finalized yet.

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
This PR adds the zone information label to the `AWSMachineClass` to allow the cluster-autoscaler scaling to/from zero.

**Which issue(s) this PR fixes**:
Fixes #77

**Special notes for your reviewer**:
/cc @hardikdr @prashanth26 

**Release note**:

```improvement user
NONE
```

### CODE REVIEW

**Comment by hardikdr** [comment]
Release notes could be in lines of:
```
Adding `zone` label on MachineClasses. Cluster autoscaler will consume it to scale-from zero for statefulset based workload.
```

I am yet to make changes to autoscaler to use this label, for it to work properly.

**Comment by rfranzke** [comment]
@hardikdr release note adapted

**Comment by rfranzke** [comment]
Let's go ahead and merge this PR - this way the AWS extension is ready already once the cluster-autoscaler is released.
@hardikdr as the CA change is still WIP, would it make sense to remove the release note from this PR and rather add it to the cluster-autoscaler later on?

**Comment by hardikdr** [comment]
> @hardikdr as the CA change is still WIP, would it make sense to remove the release note from this PR and rather add it to the cluster-autoscaler later on?

Sure, sounds good to me.

**Comment by rfranzke** [comment]
👍 removed release note + merging.

**Pull request merged**
