### PR TITLE
parallel infrastructure tests

### PR DESCRIPTION
**Pull request by kon-angelo**
**How to categorize this PR?**

/area testing
/kind enhancement
/platform aws

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by kon-angelo** [comment]
@hebelsan can I get a review ?

**Review by hebelsan — APPROVED** [review]
/lgtm

**Pull request merged**
