### PR TITLE
Add Support for Configuring CPU Options

### PR DESCRIPTION
**Pull request by AndreasBurger**
**How to categorize this PR?**

/area usability
/kind enhancement
/platform aws

**What this PR does / why we need it**:
Adds support for configuring CPU Options on instances in AWS

**Special notes for your reviewer**:
Depends on changes in https://github.com/gardener/machine-controller-manager-provider-aws/pull/161

**Release note**:

```feature user
CPU Options for AWS instances can now be set in the worker config.
```

### CODE REVIEW

**Comment by AndreasBurger** [comment]
Tests look good and requirements have been merged
@kon-angelo fyi

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
