### PR TITLE
Vendor gardener/gardener@v1.62.0

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind enhancement
/platform aws

**What this PR does / why we need it**:
Vendor `github.com/gardener/gardener@v1.62.0`.

**Which issue(s) this PR fixes**:
Prerequisite for https://github.com/gardener/gardener/issues/6773

**Release note**:

```other operator
The following dependency is updated:
- github.com/gardener/gardener: v1.59.0 -> v1.62.0
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
I rebased to "fix" the `Release Milestone Check`.

@MartinWeindel you could close https://github.com/gardener/gardener-extension-provider-aws/milestone/32 as the v1.41 release is already cut. Such open milestone is still blocking non-rebased PRs.

**Review by kon-angelo — COMMENTED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]

**Pull request merged**
