### PR TITLE
fix arm64 type for bastion instance

### PR DESCRIPTION
**Pull request by tedteng**
**How to categorize this PR?**

/area ops-productivity
/kind task
/platform aws

**What this PR does / why we need it**:
As AMI Image changed to arm64 processor Architecture `gardenlinux-aws-gardener_prod-arm64` , the original `t2.nano` with x86_64 is not supported. add a new instance type `t4g.nano` with arm64 architecture

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/694

**Special notes for your reviewer**:

**Release note**:

```other operator
add an extra t4g.nano(arm64) processor architecture bastion instance to support for linux/arm64
```

### CODE REVIEW

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Comment by petersutter** [comment]
Hi Ted,
there are some things that can be improved in my opinion, however I'm not firm with the aws api so take it with a grant of salt :)
- consider ALL images of the ami, not just the first
- use the supported-architecture filter when searching for instance types
- pass the t* types list to the `DescribeInstanceTypesWithContext` function, instead of calling it for every single one in a loop
- it uses `x86_64` instead of `amd64` as architecture. This was a bug in your code in my opinion. Fixing this we can also get rid of the unnecessary `convertName` mapping function
- also you had no fallback-preferredType (no `default` in your switch) in case the architecture is unknown

Here is my suggestion (not tested!). Please note that it makes use of the new generic implementation of `k8s.io/apimachinery/pkg/util/sets` `sets.New`. For this you have to revendor `k8s.io/apimachinery` >= v0.26
```go
func getImages(ctx context.Context, ami string, awsClient *awsclient.Client) ([]*ec2.Image, error) {
	imageInfo, err := awsClient.EC2.DescribeImagesWithContext(ctx, &ec2.DescribeImagesInput{
		ImageIds: []*string{
			aws.String(ami),
		},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get Images Info: %w", err)
	}

	if len(imageInfo.Images) == 0 {
		return nil, fmt.Errorf("images info not found: %w", err)
	}

	return imageInfo.Images, nil
}

func determineInstanceType(ctx context.Context, imageID string, awsClient *awsclient.Client) (string, error) {
	images, err := getImages(ctx, imageID, awsClient)
	if err != nil {
		return "", err
	}

	imageArchitectures := sets.New[*string]()
	for _, image := range images {
		if image.Architecture == nil {
			continue
		}
		imageArchitectures.Insert(image.Architecture)
	}

	offerings, err := awsClient.EC2.DescribeInstanceTypeOfferingsWithContext(ctx, &ec2.DescribeInstanceTypeOfferingsInput{})
	if err != nil {
		return "", fmt.Errorf("failed to list instance types: %w", err)
	}

	tTypes := make([]*string, len(offerings.InstanceTypeOfferings))
	for i, offering := range offerings.InstanceTypeOfferings {
		// we are only interested in instance types starting with `t`
		if offering.InstanceType == nil || !strings.HasPrefix(*offering.InstanceType, "t") {
			continue
		}
		tTypes[i] = offering.InstanceType
	}

	preferredTypes := sets.New[string]()
	for imageArchitecture, _ := range imageArchitectures {
		switch *imageArchitecture {
		case "arm64":
			preferredTypes.Insert("t4g.nano")
		case "x86_64":
		default:
			preferredTypes.Insert("t2.nano")
		}
	}

	for _, t := range tTypes {
		if _, ok := preferredTypes[*t]; ok {
			return *t, nil
		}
	}

	instanceTypeOutput, err := awsClient.EC2.DescribeInstanceTypesWithContext(ctx, &ec2.DescribeInstanceTypesInput{
		Filters: []*ec2.Filter{
			{
				Name:   aws.String("processor-info.supported-architecture"),
				Values: imageArchitectures.UnsortedList(),
			},
		},
		InstanceTypes: tTypes,
	})
	if err != nil {
		return "", fmt.Errorf("failed to describe instance types %v: %w", tTypes, err)
	}

	if len(instanceTypeOutput.InstanceTypes) == 0 {
		return "", fmt.Errorf("no t.* instance type available")
	}

	// fallback to the first (hopefully smallest) other general purpose instance type
	return *instanceTypeOutput.InstanceTypes[0].InstanceType, nil
}
```

**Comment by kon-angelo** [comment]
@tedteng I reverted the PR because the bastion tests fail. Please open a new PR with the bastion test fixes

**Comment by tedteng** [comment]
Thanks Peter ,  just some thoughts 
```
func getImages(ctx context.Context, ami string, awsClient *awsclient.Client) ([]*ec2.Image, error) {
```
an node ami(eg ami-1234) passed in `getImages` which get from cloudProfileConfig. then return full image info. I noticed from aws side the`imageInfo.Images` field is slices type ([]*ec2.Image). I guess that the reason this method return `[]*ec2.Image` . I don't know why is slices, I guess it may use for ami alias mapping to one ami.  then I think maybe just return `*ec2.Image`, in this way we don't need to introduce `sets` ,`imageArchitectures := sets.New[*string]()` and the relevant code . 

image

**Comment by petersutter** [comment]
Hi Ted, I agree.

As we pass the image ID and only one to `DescribeImagesWithContext` we should only expect up to one image to be returned as the images ids are unique. 
-> We do not need to consider multiple images in the response and can revert the behaviour of `getImages` to your implementation
I ~~crossed~~ this point out in my list above. Thanks

**Comment by tedteng** [comment]
New PR is ready in https://github.com/gardener/gardener-extension-provider-aws/pull/707 and some logic changed per feedback

**Pull request merged**
