### PR TITLE
Deduplicate livenessProble for admission-aws deployment

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area quality
/kind bug
/platform aws

**What this PR does / why we need it**:
Deduplicate livenessProble for admission-aws deployment. Also fix the path to the metrics port value.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Review by ialidzhikov — DISMISSED** [review]
/lgtm

**Comment by vpnachev** [comment]
I just pushed one more small fix in the same file, as I think it is too small to open another PR for it.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
