### PR TITLE
Vendor `gardener@1.80.3`, Upgrade go, `k8s.io/*` dependencies and controller-runtime

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
- Vendor `gardener@1.80.3`.
- Update go
- Upgrade k8s dependencies and controller-runtime

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
The following dependency is updated:
- github.com/gardener/gardener: v1.77.5 -> v1.80.3
- k8s.io/* : v0.26.4 -> v0.28.2
- sigs.k8s.io/controller-runtime: v0.14.6-> v0.16.2
```

### CODE REVIEW

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Comment by kon-angelo** [comment]
@shafeeqes can you look into the verify step failure ?

**Comment by shafeeqes** [comment]
Done, PTAL!

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
