### PR TITLE
Update ClusterRoles for MCM

### PR DESCRIPTION
**Pull request by prashanth26**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement
/platform aws

**What this PR does / why we need it**:
The new rule allows listing and watching of `PodDisruptionBudgets` required by newer versions of MCM
Refer - https://github.com/gardener/machine-controller-manager-provider-aws/pull/23

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
This is similar to the changes that were made on [other providers](https://github.com/gardener/gardener-extension-provider-openstack/blame/master/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml#L63-L69)

**Release note**:

```other operator
NONE
```

/invite @ialidzhikov

### CODE REVIEW

**Comment by prashanth26** [comment]
No, this change is going to be a part of the upcoming `MCM-provider-aws` release. Hence raising this PR before creating the release. Will create the release for MCM in the next few days.

**Comment by rfranzke** [comment]
Similar to https://github.com/gardener/gardener/pull/3828, let's wait until the release is cut and only merge such changes together with the version bump.

/hold

**Comment by prashanth26** [comment]
> Similar to [gardener/gardener#3828](https://github.com/gardener/gardener/pull/3828), let's wait until the release is cut and only merge such changes together with the version bump.
> 
> /hold

Okay sure.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
