### PR TITLE
Add ready check for webhook server

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area open-source
/kind enhancement
/platform aws

**What this PR does / why we need it**:
The PR adds ready check for webhook server. The ready check wait for 10 sec for webhook server to be ready, otherwise throws error.

**Which issue(s) this PR fixes**:
Part of gardener/gardener#4772

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by dkistner** [comment]
@acumino Do you want to apply similar changes like in https://github.com/gardener/gardener-extension-provider-openstack/pull/421 also here?
/rebase

**Comment by dkistner** [comment]
@acumino Do you want to apply similar changes like in https://github.com/gardener/gardener-extension-provider-openstack/pull/421 also here?
/rebase

**Comment by acumino** [comment]
> @acumino Do you want to apply similar changes like in [gardener/gardener-extension-provider-openstack#421](https://github.com/gardener/gardener-extension-provider-openstack/pull/421) also here? /rebase

I was waiting for PR in provider-openstack to be merged so that I can get all the possible required changes. and only once I have to make similar changes for PRs in other provider extensions.

**Comment by dkistner** [comment]
Fair. Now you should be able to go on. Thank you.

**Review by kon-angelo — COMMENTED** [review]
Just a small nit/question from me. On `cmd/gardener-extension-provider-aws/app/app.go` you didn't add `HealthBindAddress: ":8081"`  on `controllercmd.ManagerOptions`. 

If i am not mistaken it should be defaulted by the cmd flag, but I want to ask you to make sure. Otherwise lgtm.

**Comment by acumino** [comment]
> Just a small nit/question from me. On `cmd/gardener-extension-provider-aws/app/app.go` you didn't add `HealthBindAddress: ":8081"` on `controllercmd.ManagerOptions`.
> 
> If i am not mistaken it should be defaulted by the cmd flag, but I want to ask you to make sure. Otherwise lgtm.

I somehow missed it, though it can take the default value.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
