### PR TITLE
Update EBS driver

### PR DESCRIPTION
**Pull request by kon-angelo**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform aws

**What this PR does / why we need it**:

This PR upgrades the EBS CSI driver and installs one additional sidecar to allow live volume modifications.
(see: https://github.com/awslabs/volume-modifier-for-k8s and https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1600)

Note that there are not much data for the new side-car so the requests/limits might change soon once we know more from operating it.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Update ebs driver to `v1.19.0`
```
```feature user
Enable awslabs/volume-modifier-for-k8s by default
```

### CODE REVIEW

**Review by dkistner — APPROVED** [review]
/lgtm

**Comment by kon-angelo** [comment]
@dkistner  I needed to add the ServiceAccount line in the `valuesprovider.go`. PTAL :)

**Review by dkistner — APPROVED** [review]
/lgtm

**Pull request merged**
