### PR TITLE
Revendor gardener/gardener@a8ccc6c

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
This PR revendors gardener/gardener@a8ccc6c.

**Special notes for your reviewer**:
The `.github` PR/issue templates are now automatically copied and modified from the gardener/gardener project on revendoring.

**Release note**:

```improvement user github.com/gardener/gardener #2348 @rfranzke
The generic `Worker` actuator does now exit its reconciliation flows early if it detects an error during the machine reconciliation. This allows to faster propagate problems to the end-user.
```
```improvement user github.com/gardener/gardener #2289 @rfranzke
The extension health check library does now allow individual health checks to return the `Progressing` status. This allows to provide more accurate status information and less false negative health reports.
```
```improvement operator github.com/gardener/gardener #2290 @danielfoehrKn
The Gardenlet sets an additional annotation to Extension CRDs during reconciliation to guarantee an update event for the watching clients.
```
```improvement operator github.com/gardener/gardener #2290 @danielfoehrKn
Fixes a bug in the extension libraries that could lead to duplicate reconciliation of extension resources. When respecting the operation annotation set by the Gardenlet during reconciliation, extension controllers now only watch the Extension CRD.
```
```improvement operator github.com/gardener/gardener #2279 @danielfoehrKn
Fixes a bug in the extension library of all extension resources that lead to not stopping the reconciliation of extension resources when the Shoot is in 'failed' state (Shoot.Status.lastOperation.state = Failed). 
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
I get some diff after make revendor
```
$ git diff --shortstat
 3 files changed, 4 insertions(+), 8 deletions(-)
```

```diff
-/priority normal
-/platform aws
+/priority normaln/platform aws
```

Can you reproduce or it is related to the bash version?

The thing with .github/ - it is fine for now (I don't have in mind something better for now) but I am concerned with some things - go modules do not seem to be the right way for getting non-go files as we are doing some hacks now; I wouldn't vendor g/g in project x only to get `.github/` or common ci pipeline definitions.
As I said I don't have in mind something better for now, just thinking aloud.

**Comment by rfranzke** [comment]
```
$ make revendor
warning: ignoring symlink /Users/d065849/go/src/github.com/gardener/gardener-extension-provider-aws/charts/internal/seed-controlplane/charts/cloud-controller-manager/charts/utils-tls-cipher-suites
warning: ignoring symlink /Users/d065849/go/src/github.com/gardener/gardener-extension-provider-aws/charts/internal/seed-controlplane/charts/cloud-controller-manager/charts/utils-tls-cipher-suites

d065849 at C02YX4AELVDR in ~/go/src/github.com/gardener/gardener-extension-provider-aws on revendor/g/g1.5 at docker-desktop (15:48:05)
$ git s
On branch revendor/g/g1.5
nothing to commit, working tree clean
```

Do you have GNU sed as suggested? https://github.com/gardener/gardener/blob/master/hack/install-requirements.sh#L25-L40

**Comment by ialidzhikov** [comment]
> Do you have GNU sed as suggested?

It works after `brew install gnu-sed` and `export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"`. Probably it make sense to add also `gnu-sed` to install-requirements.sh?

**Comment by rfranzke** [comment]
What exactly do you want to add? The [instructions](https://github.com/gardener/gardener/blob/master/hack/install-requirements.sh#L25-L40) for Mac users are already explained. Probably #22 is what we rather should invest to get finally rid of this problem class.

**Comment by ialidzhikov** [comment]
> What exactly do you want to add? The instructions for Mac users are already explained.

install-requirements.sh only suggest about coreutils and gnu-tar but not gnu-sed. I had coreutils and gnu-tar already installed. Now gnu-sed also seems be to required for extension repos.

**Comment by rfranzke** [comment]
Ah, I see, thanks. Yes, will do, thank you.

**Comment by rfranzke** [comment]
https://github.com/gardener/gardener/pull/2362

Thanks for approving.
/merge

**Pull request merged**
