### PR TITLE
Scale down if custom-route-controller is disabled after creation

### PR DESCRIPTION
**Pull request by MartinWeindel**
**How to categorize this PR?**

/area control-plane
/kind bug
/platform aws

**What this PR does / why we need it**:
If a shoot is created with `aws-custom-route-controller` enabled and the controller is disabled later by setting `cloudControllerManager.useCustomRouteController=false` in the `ControlPlaneConfig`, the deployment is not removed.
The control plane deployment cannot deal with such cases. Looks like a minor edge case to me, therefore the fix just scales down the deployment.

Additionally a non-relevant typo was fixed in `charts/internal/seed-controlplane/values.yaml` 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
Is it not cleaner to not deploy the corresponding charts if the controller is disabled? based on the `enabled` field?

**Comment by shafeeqes** [comment]
Okay, this chart is not part of any managed resource? Then my suggestion won't probably work because the resources won't be cleaned up.

**Review by dkistner — APPROVED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
FYI, this PR does not fix/mitigate anything - see https://github.com/gardener/gardener-extension-provider-aws/issues/628.

**Pull request merged**
