### PR TITLE
add getImageAMI for sustainable test

### PR DESCRIPTION
**Pull request by tedteng**
**How to categorize this PR?**

/area ops-productivity
/kind enhancement
/platform aws

**What this PR does / why we need it**:
add a "sustainable" way to get available image AMIs for the test 

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/713

**Special notes for your reviewer**:

**Release note**:

```other operator
add a sustainable way to get available image AMIs for the test
```
/invite @kon-angelo

### CODE REVIEW

**Comment by kon-angelo** [comment]
I am not sure about the particulars of the image, but should we maybe try to use the `server` type images ? I think this is not guaranteed as it. Maybe with an small adaptation to the glob pattern ?

**Comment by tedteng** [comment]
done change to `ubuntu-*server*` type image
/test

**Comment by tedteng** [comment]
@kon-angelo I did some testing after changing to `ubuntu-*server*` type image, however, it bring one issue let me whether still need more effort to resolve this by using `server` type image, or just keep the current solution. 
`error reconciling Bastion: failed to ensure bastion instance: failed to run instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=f165x13dfhzd2xbgnkvs6s5tr\n\tstatus code: 401, `

**Comment by tedteng** [comment]
just check `ubuntu-jammy*`, the full image name `ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230208`, is this the `server` type image you mentioned?

**Comment by tedteng** [comment]
@kon-angelo Can this PR be processed?

**Comment by tedteng** [comment]
@kon-angelo Can we process this PR? Thanks

**Pull request merged**
