### PR TITLE
support extended resources in providerConfig.nodeTemplate, inherit core resources from pool.nodeTemplate

### LINKED ISSUE #1009: Support extended resources in provider config node template without re-specifying core resources
**How to categorize this issue?**

/area auto-scaling
/kind enhancement
/platform aws

**What would you like to be added**:

Permit specification of custom extended resources in the `worker.providerConfig.nodeTemplate` without needing to explicitly re-specify core resources such as `cpu`, `gpu`, `memory` for the machine type again.   

**Why is this needed**:
This is needed for support of https://github.com/gardener/autoscaler/issues/132.  This will permit stakeholders to have custom extended resources associated with `Nodes`, thus permitting `Pods` specs with requests for these custom extended resources and leveraging the scheduling support by the `kube-scheduler` 

(see HANA-27484 for extended details)

### PR DESCRIPTION
**Pull request by elankath**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement
/platform aws

**What this PR does / why we need it**:

Permit specification of custom extended resources in the `worker.providerConfig.nodeTemplate` without needing to explicitly re-specify core resources such as `cpu`, `gpu`, `memory` for the machine type again.

**Which issue(s) this PR fixes**:
Fixes #1009

**Special notes for your reviewer**:

**Release note**:

```feature operator
Support specification of extended resources in provider config node template without re-specifying core resources.
```

### CODE REVIEW

**Comment by elankath** [comment]
@kon-angelo  could you review this. I would like to add a unit test. But I need the unit test to check `workerDelegate.machineClasses` to see if extended resources have been set in.  Unfortunately, it is un-exported field in the `workerDelegate`.  Is it OK to introduce a method to expose this ? (Inside `pkg/controller/worker/actuator.go`) ?

**Comment by elankath** [comment]
This PR will be closed and a fresh one re-opened with latest changes. Sorry for delay.

**Comment by elankath** [comment]
Re-based with latest changed and simplified.

**Comment by elankath** [comment]
@kon-angelo  I would like to make [worker.workerDelegate](https://github.com/gardener/gardener-extension-provider-aws/blob/6e7fa296e9af0a0fe3ebd8745b798309ebca022a/pkg/controller/worker/actuator.go#L86) type as exported ie make it `worker.WorkerDelegate` to enable unit-test that checks `machineClasses` inside this type. The problem is that our test code is in a different package `worker_test` and hence cannot accerss `workerDelegate`. Please give me a go to do this and I will add additional unit-tests for this PR.

**Comment by elankath** [comment]
/assign kon-angelo
/assign MartinWeindel

Can you take a look to see if this is OK or requires changes ?

**Review by AndreasBurger — APPROVED** [review]

**Pull request merged**
